package pictzr.zerogvt.org;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ImagePlayerTest {
    @Test public void testSomeLibraryMethod() {
        ImagePlayer classUnderTest = new ImagePlayer();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.isImage(filepath)());
    }
}
