package pictzr.zerogvt.org;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class PicTeaserTest {
    @Test public void testSomeLibraryMethod() {
        PicTeaser classUnderTest = new PicTeaser();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.isImage(filepath)());
    }
}
